@startuml


skinparam backgroundColor #EEEBDC

legend top left
 |= Color  |= Package |
 |<back:#a2ebaa>   </back>| Package1 |
 |<back:#a2c5eb>   </back>| Package2 |
 |<back:#dea2eb>   </back>| Package3 |

 endlegend


abstract class Animal #a2ebaa{
    -nombrePattes: int
    -couleur: String

    #faireBruit(): Bruit
    +marcher()
}


class Dog #a2c5eb extends Animal {
    +aboyer(): Bruit
}

class Bruit #dea2eb {

    -sonProduit: String
    +getSonProduit(): String
}


Animal --r-> Bruit
Dog -up--o Bruit


@enduml
